### ISSUE TITLE
Speed when scrolling

### ISSUE THREAD

**Issue by uncleho** [eoghain/RBCollectionViewInfoFolderLayout#8]
I find that when I use this code with a bunch of items (like hundreds), scrolling is incredibly slow. Is this a problem with the custom layout?

**Comment by eoghain** [comment]
If you are using the **Sticky Headers** this could cause you some scrolling slowdown as it has to re-calculate the positions of all items in the collectionView every time it moves.  If you aren't using **Sticky Headers** then the calculations are only done when expected (adding/removing items, or resizing collectionView).

**Comment by uncleho** [comment]
Thanks!
